### ISSUE TITLE
Setting a parser for application/x-www-form-urlencoded does not work

### ISSUE THREAD

**Issue by lasse-unity3d** [vasekd/Plack-Middleware-ParseContent#1]
It can be useful to be able to override the default behaviour for requests with Content-Type: application/x-www-form-urlencoded because some broken clients like to send e.g. JSON bodies without setting the proper Content-Type.

This does not work:

``` perl
enable 'ParseContent', 'application/x-www-form-urlencoded' => sub { decode_json($_[0]) };
```

...because the handling for application/x-www-form-urlencoded kicks in before the custom handlers are checked.

**Comment by vasekd** [comment]
Fixed in version 0.05 by commit: [fb8c288](https://github.com/vasekd/Plack-Middleware-ParseContent/commit/fb8c288541d0b76ffba7ef334f7c5fff53da3c3d)

Thank you
